version: '3'
services:

  database:
    image: mysql:8.0.15
    restart: always
    container_name: geolocations_platform_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    security_opt:
      - seccomp:unconfined

  locations-platform_backend:
    restart: always
    build:
      context: ../backend
    container_name: geolocations_platform_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database
    ports:
      - "8080:8080"